FORMAT: 1A
HOST: http://polls.apiblueprint.org/
# Motiva

Descrição da API do Motiva

## Upload de imagem de uma postagem [/upload/post_image]
### Upload Post Image [POST]
Faz upload da imagem de imagem de uma postagem

+ Request (form-data)
    + Headers
        Authorization: Bearer <user_key_auth> (required, String) - OAuth2.0 Bearer Token authorization
    + Attributes
        + image_file: [File] (required, File) - File of a post image.
        + post_id: "1" (required, Text) - ID of a post

+ Response 200 (application/json)
    + Body
            {
                "status": true,
                "result": {
                    "message": "Upload realizado com sucesso",
                    "filename": "/media/<file_name>.jpg"
                }
            }

## Login [/login]
### Login [POST]
Realiza login através de nome de usuário e senha

+ Attributes
    + username: renan (required, string) - Username of a user.
    + password: 123456 (required, string) - Password of a user.

+ Request (application/json)

+ Response 200 (application/json)
    + Body

            {
                "status": true,
                "data": {
                    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9..."
                    "username": "lcleite",
                    "user_id": 1,
                    "active": true
                }
            }


# Group User
Ações relacionadas ao usuário

## Dados do Usuário [/user/{username}]
### Get User [GET]

Solicita os dados do perfil de um usuário

+ Request (application/json)
    + Headers

            Authorization: Bearer <user_key_auth> (required, String) - OAuth2.0 Bearer Token authorization

    + Parameters
        + username: "renan" (required, String) - Username of some user.

+ Response 200 (application/json)

    + Body

            {
                "status": true,
                "result":
                {
                    "first_name": "Renan",
                    "last_name": "Hozumi",
                    "description": "string",
                    "username": "renanhb",
                    "avatar_url": "https://source.unsplash.com/random/200x200",
                    "email": "renan.hbarbieri@gmail.com",
                    "facebook": "@renanhb",
                    "github": "@renanBarbieri",
                    "linkedin": "string",
                    "level":
                    {
                        "name": "Profissional"
                    },
                    "achievements":
                    [
                        {
                            "id": 20,
                            "image_url": "https://source.unsplash.com/random/80x80",
                            "name": "Coração de ouro",
                            "description": "bla bla bla wiskas sache"
                        },
                        {
                            "id": 30,
                            "image_url": "https://source.unsplash.com/random/80x80",
                            "name": "Coração de prata",
                            "description": "bla bla bla wiskas sache"
                        },
                        {
                            "id": 32,
                            "image_url": "https://source.unsplash.com/random/80x80",
                            "name": "Coração de bronze",
                            "description": "bla bla bla wiskas sache"
                        },
                        {
                            "id": 18,
                            "image_url": "https://source.unsplash.com/random/80x80",
                            "name": "Na direção certa",
                            "description": "bla bla bla wiskas sache"
                        },
                        {
                            "id": 78,
                            "image_url": "https://source.unsplash.com/random/80x80",
                            "name": "Reta Final",
                            "description": "bla bla bla wiskas sache"
                        },
                        {
                            "id": 56,
                            "image_url": "https://source.unsplash.com/random/80x80",
                            "name": "Na direção certa",
                            "description": "bla bla bla wiskas sache"
                        }
                    ],
                    "interests":
                    [
                        {
                            "name": "Swift",
                            "id": 23
                        },
                        {
                            "name": "Python",
                            "id": 34
                        },
                        {
                            "name": "Objective-C",
                            "id": 65
                        },
                        {
                            "name": "Ruby",
                            "id": 2
                        }
                    ]
                }
            }
# Group Topics
Ações relacionadas aos topicos
## Posts de um tópico [/tag/{id}/posts?limit={limit}]
### Get Posts [GET]

Solicita os posts de uma tag

+ Parameters
    + id: 2 (required, Number) - Id of tag.
    + limit: 4 (optional, Number) - Limit number of articles
        + Default: 4

+ Request (application/json)
    + Headers

            Authorization: user_key_auth (required, String) - Key authorization

+ Response 200 (application/json)

    + Body

            {
                "status": true,
                "result":
                [
                    {
                        "id": 23,
                        "title": "Titulo do Artigo 0",
                        "subtitle": "Esse é um subtitulo",
                        "favorites": 19,
                        "likes": 5,
                        "image_url": "https://source.unsplash.com/random/100x100",
                        "publishDate": 1519495297000,
                        "editedDate": 1519495297000,
                        "owner": {
                            "avatar_url": "https://source.unsplash.com/random/80x80",
                            "name": "Usuario de teste",
                            "id": 76
                        }
                    },
                    {
                        "id": 23,
                        "title": "Titulo do Artigo 2",
                        "subtitle": "Esse é um subtitulo",
                        "favorites": 3,
                        "likes": 11,
                        "image_url": "https://source.unsplash.com/random/100x100",
                        "publishDate": 1519495297000,
                        "editedDate": 1519495297000,
                        "owner": {
                            "avatar_url": "https://source.unsplash.com/random/80x80",
                            "name": "Usuario de teste 3",
                            "id": 43
                        }
                    },
                    {
                        "id": 23,
                        "title": "Titulo do Artigo 3",
                        "subtitle": "Esse é um subtitulo",
                        "favorites": 6,
                        "likes": 1,
                        "image_url": "https://source.unsplash.com/random/100x100",
                        "publishDate": 1519495297000,
                        "editedDate": 1519495297000,
                        "owner": {
                            "avatar_url": "https://source.unsplash.com/random/80x80",
                            "name": "Usuario de teste 2",
                            "id": 56
                        }
                    },
                    {
                        "id": 23,
                        "title": "Titulo do Artigo 4",
                        "subtitle": "Esse é um subtitulo",
                        "favorites": 4,
                        "likes": 10,
                        "image_url": "https://source.unsplash.com/random/100x100",
                        "publishDate": 1519495297000,
                        "editedDate": 1519495297000,
                        "owner": {
                            "avatar_url": "https://source.unsplash.com/random/80x80",
                            "name": "Usuario de teste 3",
                            "id": 43
                        }
                    }
                ]
            }

# Group Tools
Ações relacionadas a ferramentas
## Pesquisa [/search?q={query}&limit={limit}]
### Get Result [GET]
+ Parameters
    + query: "teleprocessamento" (required, String) - Query for search.
    + limit: 4 (optional, Number) - Limit number of result. -1 is unlimited
        + Default: 10

+ Request (application/json)
    + Headers

            Authorization: user_key_auth (required, String) - Key authorization

+ Response 200 (application/json)

    + Body

            {
                "status": true,
                "result":
                {
                    "users":[
                        {
                            "avatar": "https://source.unsplash.com/random/80x80",
                            "name": "Usuario de teste 3",
                            "id": 43
                        },
                        {
                            "avatar": "https://source.unsplash.com/random/80x80",
                            "name": "Usuario de teste 3",
                            "id": 34
                        },
                        {
                            "avatar": "https://source.unsplash.com/random/80x80",
                            "name": "Usuario de teste 3",
                            "id": 13
                        },
                        {
                            "avatar": "https://source.unsplash.com/random/80x80",
                            "name": "Usuario de teste 3",
                            "id": 32
                        },
                        {
                            "avatar": "https://source.unsplash.com/random/80x80",
                            "name": "Usuario de teste 3",
                            "id": 28
                        },
                        {
                            "avatar": "https://source.unsplash.com/random/80x80",
                            "name": "Usuario de teste 3",
                            "id": 45
                        }
                    ],
                    "tags":[
                        {
                            "name": "Java",
                            "id": 23
                        },
                        {
                            "name": "JavaScript",
                            "id": 34
                        },
                        {
                            "name": "JavaServer Faces",
                            "id": 65
                        },
                        {
                            "name": "Java Reflection",
                            "id": 2
                        }
                    ],
                    "posts":[
                        {
                            "id": 23,
                            "title": "Titulo do Artigo 0",
                            "subtitle": "Esse é um subtitulo",
                            "favorites": 4,
                            "likes": 10,
                            "image": "https://source.unsplash.com/random/100x100",
                            "publishDate": 1519495297000,
                            "editedDate": 1519495297000,
                            "owner": {
                                "avatar": "https://source.unsplash.com/random/80x80",
                                "name": "Usuario de teste",
                                "id": 76
                            }
                        },
                        {
                            "id": 20,
                            "title": "Titulo do Artigo 2",
                            "subtitle": "Esse é um subtitulo",
                            "favorites": 2,
                            "likes": 20,
                            "image": "https://source.unsplash.com/random/100x100",
                            "publishDate": 1519495297000,
                            "editedDate": 1519495297000,
                            "owner": {
                                "avatar": "https://source.unsplash.com/random/80x80",
                                "name": "Usuario de teste 3",
                                "id": 43
                            }
                        },
                        {
                            "id": 2,
                            "title": "Titulo do Artigo 3",
                            "subtitle": "Esse é um subtitulo",
                            "image": "https://source.unsplash.com/random/100x100",
                            "favorites": 10,
                            "likes": 40,
                            "publishDate": 1519495297000,
                            "editedDate": 1519495297000,
                            "owner": {
                                "avatar": "https://source.unsplash.com/random/80x80",
                                "name": "Usuario de teste 2",
                                "id": 56
                            }
                        },
                        {
                            "id": 32,
                            "title": "Titulo do Artigo 4",
                            "subtitle": "Esse é um subtitulo",
                            "image": "https://source.unsplash.com/random/100x100",
                            "favorites": 10,
                            "likes": 4,
                            "publishDate": 1519495297000,
                            "editedDate": 1519495297000,
                            "owner": {
                                "avatar": "https://source.unsplash.com/random/80x80",
                                "name": "Usuario de teste 3",
                                "id": 43
                            }
                        },
                        {
                            "id": 33,
                            "title": "Titulo do Artigo 0",
                            "subtitle": "Esse é um subtitulo",
                            "favorites": 6,
                            "likes": 10,
                            "image": "https://source.unsplash.com/random/100x100",
                            "publishDate": 1519495297000,
                            "editedDate": 1519495297000,
                            "owner": {
                                "avatar": "https://source.unsplash.com/random/80x80",
                                "name": "Usuario de teste",
                                "id": 76
                            }
                        },
                        {
                            "id": 43,
                            "title": "Titulo do Artigo 2",
                            "subtitle": "Esse é um subtitulo",
                            "favorites": 4,
                            "likes": 10,
                            "image": "https://source.unsplash.com/random/100x100",
                            "publishDate": 1519495297000,
                            "editedDate": 1519495297000,
                            "owner": {
                                "avatar": "https://source.unsplash.com/random/80x80",
                                "name": "Usuario de teste 3",
                                "id": 43
                            }
                        },
                        {
                            "id": 56,
                            "title": "Titulo do Artigo 3",
                            "subtitle": "Esse é um subtitulo",
                            "favorites": 8,
                            "likes": 14,
                            "image": "https://source.unsplash.com/random/100x100",
                            "publishDate": 1519495297000,
                            "editedDate": 1519495297000,
                            "owner": {
                                "avatar": "https://source.unsplash.com/random/80x80",
                                "name": "Usuario de teste 2",
                                "id": 56
                            }
                        },
                        {
                            "id": 89,
                            "title": "Titulo do Artigo 4",
                            "subtitle": "Esse é um subtitulo",
                            "favorites": 12,
                            "likes": 10,
                            "image": "https://source.unsplash.com/random/100x100",
                            "publishDate": 1519495297000,
                            "editedDate": 1519495297000,
                            "owner": {
                                "avatar": "https://source.unsplash.com/random/80x80",
                                "name": "Usuario de teste 3",
                                "id": 43
                            }
                        }
                    ]
                }
            }
