FORMAT: 1A
HOST: http://polls.apiblueprint.org/
# Motiva

Descrição da API do Motiva
# Group User
Ações relacionadas ao usuário
## Dados do Usuário [/user]
### Get User [GET]

Solicita os dados do usuário

+ Request (application/json)
    + Headers
            
            Authorization: user_key_auth

+ Response 201 (application/json)

    + Body

            {
                "status": "SUCCESS",
                "result": 
                {
                    "name": "string",
                    "description": "string",
                    "username": "string",
                    "avatar": "string",
                    "email": "string",
                    "experience": "number",
                    "facebook": "string",
                    "github": "string",
                    "linkedin": "string",
                    "level": 
                    {
                        "name": "Amador",
                        "completetion": 57,
                        "nextLevelName":"Iniciante"
                    },
                    "rewards": 
                    [
                        {
                            "icon": "https://source.unsplash.com/random/80x80",
                            "name": "Coração de ouro",
                            "description": "bla bla bla wiskas sache"
                        }, 
                        {
                            "icon": "https://source.unsplash.com/random/80x80",
                            "name": "Coração de prata",
                            "description": "bla bla bla wiskas sache"
                        }, 
                        {
                            "icon": "https://source.unsplash.com/random/80x80",
                            "name": "Coração de bronze",
                            "description": "bla bla bla wiskas sache"
                        }, 
                        {
                            "icon": "https://source.unsplash.com/random/80x80",
                            "name": "Na direção certa",
                            "description": "bla bla bla wiskas sache"
                        }
                    ],
                    "interests": 
                    [
                        {
                            "name": "Swift",
                            "id": 23
                        }, 
                        {
                            "name": "Python",
                            "id": 34
                        }, 
                        {
                            "name": "Objective-C",
                            "id": 65
                        }, 
                        {
                            "name": "Ruby",
                            "id": 2
                        }
                    ]
                }
            }
# Group Topics
Ações relacionadas aos topicos
## Artigos de um tópico [/tag/{id}/articles?limit={limit}]
### Get Articles [GET]

Solicita os dados do usuário

+ Parameters
    + id: 2 (required, Number) - Id of tag.
    + limit: 4 (optional, Number) - Limit number of articles
        + Default: 4

+ Request (application/json)
    + Headers
    
            Authorization: user_key_auth (required, String) - Key authorization

+ Response 201 (application/json)

    + Body

            {
                "status": "SUCCESS",
                "result": 
                {
                    [
                        "title": "Titulo do Artigo 2",
                        "subtitle": "Esse é um subtitulo",
                        "content": "Aqui vem o texto escrito pelo autor",
                        "publishDate": 1519495297000,
                        "editedDate": 1519495297000,
                        "ownerName": "Usuario de teste"
                    ],
                    [
                        "title": "Titulo do Artigo 2",
                        "subtitle": "Esse é um subtitulo",
                        "content": "Aqui vem o texto escrito pelo autor",
                        "publishDate": 1519495297000,
                        "editedDate": 1519495297000,
                        "ownerName": "Usuario de teste"
                    ],
                    [
                        "title": "Titulo do Artigo 3",
                        "subtitle": "Esse é um subtitulo",
                        "content": "Aqui vem o texto escrito pelo autor",
                        "publishDate": 1519495297000,
                        "editedDate": 1519495297000,
                        "ownerName": "Usuario de teste 2"
                    ],
                    [
                        "title": "Titulo do Artigo 4",
                        "subtitle": "Esse é um subtitulo",
                        "content": "Aqui vem o texto escrito pelo autor",
                        "publishDate": 1519495297000,
                        "editedDate": 1519495297000,
                        "ownerName": "Usuario de teste 4"
                    ],
                }
            }