FORMAT: 1A
HOST: http://polls.apiblueprint.org/
# Motiva

Descrição da API do Motiva
# Group User
Ações relacionadas ao usuário
## Dados do Usuário [/user]
### Get User [GET]

Solicita os dados do usuário

+ Request (application/json)
    + Headers
            
            Authorization: user_key_auth (required, String) - Key authorization

+ Response 200 (application/json)

    + Body

            {
                "status": "SUCCESS",
                "result": 
                {
                    "name": "Renan",
                    "description": "string",
                    "username": "renanhb",
                    "avatar": "https://source.unsplash.com/random/200x200",
                    "email": "renan.hbarbieri@gmail.com",
                    "experience": 500,
                    "facebook": "@renanhb",
                    "github": "@renanBarbieri",
                    "linkedin": "string",
                    "level": 
                    {
                        "name": "Profissional",
                        "completetion": 90,
                        "nextLevelName":"Iniciante"
                    },
                    "rewards": 
                    [
                        {
                            "id": 20,
                            "icon": "https://source.unsplash.com/random/80x80",
                            "name": "Coração de ouro",
                            "description": "bla bla bla wiskas sache"
                        }, 
                        {
                            "id": 30,
                            "icon": "https://source.unsplash.com/random/80x80",
                            "name": "Coração de prata",
                            "description": "bla bla bla wiskas sache"
                        }, 
                        {
                            "id": 32,
                            "icon": "https://source.unsplash.com/random/80x80",
                            "name": "Coração de bronze",
                            "description": "bla bla bla wiskas sache"
                        }, 
                        {
                            "id": 18,
                            "icon": "https://source.unsplash.com/random/80x80",
                            "name": "Na direção certa",
                            "description": "bla bla bla wiskas sache"
                        }
                    ],
                    "tags": 
                    [
                        {
                            "name": "Swift",
                            "id": 23
                        }, 
                        {
                            "name": "Python",
                            "id": 34
                        }, 
                        {
                            "name": "Objective-C",
                            "id": 65
                        }, 
                        {
                            "name": "Ruby",
                            "id": 2
                        }
                    ]
                }
            }
# Group Topics
Ações relacionadas aos topicos
## Posts de um tópico [/tag/{id}/posts?limit={limit}]
### Get Posts [GET]

Solicita os posts de uma tag

+ Parameters
    + id: 2 (required, Number) - Id of tag.
    + limit: 4 (optional, Number) - Limit number of articles
        + Default: 4

+ Request (application/json)
    + Headers
    
            Authorization: user_key_auth (required, String) - Key authorization

+ Response 200 (application/json)

    + Body

            {
                "status": "SUCCESS",
                "result": 
                [
                    {
                        "id": 23,
                        "title": "Titulo do Artigo 0",
                        "subtitle": "Esse é um subtitulo",
                        "image": "https://source.unsplash.com/random/100x100",
                        "publishDate": 1519495297000,
                        "editedDate": 1519495297000,
                        "owner": {
                            "avatar": "https://source.unsplash.com/random/80x80",
                            "name": "Usuario de teste",
                            "id": 76
                        }
                    },
                    {
                        "id": 23,
                        "title": "Titulo do Artigo 2",
                        "subtitle": "Esse é um subtitulo",
                        "image": "https://source.unsplash.com/random/100x100",
                        "publishDate": 1519495297000,
                        "editedDate": 1519495297000,
                        "owner": {
                            "avatar": "https://source.unsplash.com/random/80x80",
                            "name": "Usuario de teste 3",
                            "id": 43
                        }
                    },
                    {
                        "id": 23,
                        "title": "Titulo do Artigo 3",
                        "subtitle": "Esse é um subtitulo",
                        "image": "https://source.unsplash.com/random/100x100",
                        "publishDate": 1519495297000,
                        "editedDate": 1519495297000,
                        "owner": {
                            "avatar": "https://source.unsplash.com/random/80x80",
                            "name": "Usuario de teste 2",
                            "id": 56
                        }
                    },
                    {
                        "id": 23,
                        "title": "Titulo do Artigo 4",
                        "subtitle": "Esse é um subtitulo",
                        "image": "https://source.unsplash.com/random/100x100",
                        "publishDate": 1519495297000,
                        "editedDate": 1519495297000,
                        "owner": {
                            "avatar": "https://source.unsplash.com/random/80x80",
                            "name": "Usuario de teste 3",
                            "id": 43
                        }
                    }
                ]
            }
            
# Group Tools
Ações relacionadas a ferramentas
## Pesquisa [/search?q={query}&limit={limit}]
### Get Result [GET]
+ Parameters
    + query: "teleprocessamento" (required, String) - Query for search.
    + limit: 4 (optional, Number) - Limit number of result. -1 is unlimited
        + Default: 10

+ Request (application/json)
    + Headers
    
            Authorization: user_key_auth (required, String) - Key authorization
            
+ Response 200 (application/json)

    + Body

            {
                "status": "SUCCESS",
                "result": 
                [
                    "users":[
                        {
                            "avatar": "https://source.unsplash.com/random/80x80",
                            "name": "Usuario de teste 3",
                            "id": 43
                        },
                        {
                            "avatar": "https://source.unsplash.com/random/80x80",
                            "name": "Usuario de teste 3",
                            "id": 34
                        },
                        {
                            "avatar": "https://source.unsplash.com/random/80x80",
                            "name": "Usuario de teste 3",
                            "id": 13
                        },
                        {
                            "avatar": "https://source.unsplash.com/random/80x80",
                            "name": "Usuario de teste 3",
                            "id": 32
                        },
                        {
                            "avatar": "https://source.unsplash.com/random/80x80",
                            "name": "Usuario de teste 3",
                            "id": 28
                        },
                        {
                            "avatar": "https://source.unsplash.com/random/80x80",
                            "name": "Usuario de teste 3",
                            "id": 45
                        },
                    ],
                    "tags":[
                        {
                            "name": "Java",
                            "id": 23
                        }, 
                        {
                            "name": "JavaScript",
                            "id": 34
                        }, 
                        {
                            "name": "JavaServer Faces",
                            "id": 65
                        }, 
                        {
                            "name": "Java Reflection",
                            "id": 2
                        }
                    ],
                    "posts":[
                        {
                            "id": 23,
                            "title": "Titulo do Artigo 0",
                            "subtitle": "Esse é um subtitulo",
                            "image": "https://source.unsplash.com/random/100x100",
                            "publishDate": 1519495297000,
                            "editedDate": 1519495297000,
                            "owner": {
                                "avatar": "https://source.unsplash.com/random/80x80",
                                "name": "Usuario de teste",
                                "id": 76
                            }
                        },
                        {
                            "id": 23,
                            "title": "Titulo do Artigo 2",
                            "subtitle": "Esse é um subtitulo",
                            "image": "https://source.unsplash.com/random/100x100",
                            "publishDate": 1519495297000,
                            "editedDate": 1519495297000,
                            "owner": {
                                "avatar": "https://source.unsplash.com/random/80x80",
                                "name": "Usuario de teste 3",
                                "id": 43
                            }
                        },
                        {
                            "id": 23,
                            "title": "Titulo do Artigo 3",
                            "subtitle": "Esse é um subtitulo",
                            "image": "https://source.unsplash.com/random/100x100",
                            "publishDate": 1519495297000,
                            "editedDate": 1519495297000,
                            "owner": {
                                "avatar": "https://source.unsplash.com/random/80x80",
                                "name": "Usuario de teste 2",
                                "id": 56
                            }
                        },
                        {
                            "id": 23,
                            "title": "Titulo do Artigo 4",
                            "subtitle": "Esse é um subtitulo",
                            "image": "https://source.unsplash.com/random/100x100",
                            "publishDate": 1519495297000,
                            "editedDate": 1519495297000,
                            "owner": {
                                "avatar": "https://source.unsplash.com/random/80x80",
                                "name": "Usuario de teste 3",
                                "id": 43
                            }
                        }
                    ]
                ]
            }